### PR TITLE
March 2020 Front End Re-Design

### LINKED ISSUE #8: allow user to filter tracks in queue/playlists

### LINKED ISSUE #53: song preview no longer works on very short tracks

### LINKED ISSUE #74: android keyboard interfering with scrollToBottom on chats
When an Android keyboard is open, it changes the height of the chat box -- interfering with the scrollToBottom. Because of this , chat is not scrolled to correct position when closing the keyboard.

### PR DESCRIPTION
**Pull request by mxew**

### CODE REVIEW

**Comment by ghost** [comment]
p- push it reeeeal good!

**Comment by cyancey76** [comment]
@andrewtibbetts I'm not sure I like the @ notification layout. With the inline chat links being bright orange, and the @ symbol being on the right, relatively small, the links really take over your attention and your @ messages aren't obvious

**Comment by mxew** [comment]
Found some mobile width and text size bugs that need squashed. More details to come.

**Comment by mxew** [comment]
IMG_3263
Chat seems to be overflowing on mobile, font-size huge in now playing messages, currentTheme text-overflow broken

**Comment by mxew** [comment]
Oh apparently the history button is broken also... I'll fix that one.

**Comment by mxew** [comment]
@andrewtibbetts @rklados any new information on the yt embed loading issue?

**Comment by ghost** [comment]
> @andrewtibbetts I'm not sure I like the @ notification layout. With the inline chat links being bright orange, and the @ symbol being on the right, relatively small, the links really take over your attention and your @ messages aren't obvious

I'm with ya. The orange @ was kind of a hasty solution. And orange should be mostly reserved for things that are actionable. I have an idea.

**Comment by chrisrohn** [comment]
Add a setting to turn off avatars in chat please thanks :)

**Pull request merged**
